services:
  # Backend
  api:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - app-weather-network
    env_file: "./.env"
  
  # Frontend
  app:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - app-weather-network
    env_file: "./.env"
    command: npm start

networks:
  app-weather-network:
    driver: bridge
